version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/starwars_api
    env_file:
      - .env
    command: sh -c "dockerize -wait tcp://db:5432 -timeout 300s -wait-retry-interval 30s sh deploy.sh"
