# Generated by Django 4.0.2 on 2022-02-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_options_person_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
