# Generated by Django 4.0.2 on 2022-02-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('people', '0004_alter_person_species_alter_person_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='species',
            field=models.ManyToManyField(blank=True, to='people.Specie'),
        ),
        migrations.AlterField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='vehicles.Vehicle'),
        ),
    ]
