# Generated by Django 4.0.2 on 2022-02-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_species_alter_person_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name_plural': 'People'},
        ),
    ]
