# Generated by Django 4.0.2 on 2022-02-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_person_species_person_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='species',
            new_name='specie',
        ),
    ]
