# Generated by Django 4.0.2 on 2022-02-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_birth_date'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(null=True, to='people.Person'),
        ),
    ]
