# Generated by Django 4.0.2 on 2022-02-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_species_alter_person_vehicles'),
        ('films', '0002_alter_film_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
    ]
